'use client'

import './globals.css'
import 'react-toastify/dist/ReactToastify.css'
import { ToastContainer } from 'react-toastify'

import { Provider } from 'react-redux'

const metadata = {
  title: 'fundus',
  description: 'Generated by create-solana-dapp',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-white">
       <div>
        {children}
       </div>
      </body>
    </html>
  )
}
